name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build and Run AIStore
        uses: gaikwadabhishek/aistore@master
      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      # Runs a single command using the runners shell
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Runs a set of commands using the runners shell
      - name: Install test requirements
        run: pip3 install -r requirements.txt
      - name: check if AIS is running
        shell: bash
        run: |
          ais bucket ls
          ais create bucket ais://bucket1
      - name: Run tests with pytest
        run:
          pytest tests
