name: Path Based Environment Variables

on:
  workflow_dispatch:
        inputs:
          check_version:
            description: 'I confirm that I have verified [version](https://github.com/NVIDIA/aistore/blob/main/python/aistore/version.py) to be published'
            required: true
            type: boolean
            default: false  

  push:
    paths:
      - 'pathA/**'
      - 'pathB/**'
env:
  PATHA: false
jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Paths
        id: paths_filter
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: dorny/paths-filter@v2
        with:
          filters: |
            pathA:
              - 'pathA/**'
            pathB:
              - 'pathB/**'

      - name: Set PATHA
        if: steps.paths_filter.outputs.pathA == 'true'
        run: echo "PATHA=true" >> $GITHUB_ENV

      - name: Set PATHB
        if: steps.paths_filter.outputs.pathB == 'true'
        run: echo "PATHB=true" >> $GITHUB_ENV

      # Example step that uses the set environment variables
      - name: Use the Environment Variables
        run: |
          echo "Path A changed: ${{ env.PATHA }}"
          echo "Path B changed: ${{ env.PATHB }}"
      - name: ECHO TEST SECRET
        run: |
          echo ${{ secrets.KAGGLE_CREDS_JSON }} > kaggle_creds.json
          cat kaggle_creds.json
