name: Set Conditional Path Variables

on: 
  push:
    paths: 
      - 'pathA/**'
      - 'pathB/**'

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes in pathA
        id: path_a_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'pathA/'
          then
            echo "PATHA=true" >> $GITHUB_ENV
          fi

      - name: Check for changes in pathB
        id: path_b_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'pathB/'
          then
            echo "PATHB=true" >> $GITHUB_ENV
          fi

      # Example step that uses the set environment variables
      - name: Use the Environment Variables
        run: |
          echo "Path A changed: ${{ env.PATHA }}"
          echo "Path B changed: ${{ env.PATHB }}"
