name: Path Based Environment Variables

on:
  workflow_dispatch:
  push:
    paths:
      - 'pathA/**'
      - 'pathB/**'
env:
  PATHA: false
jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Paths
        id: paths_filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            pathA:
              - 'pathA/**'
            pathB:
              - 'pathB/**'

      - name: Set PATHA
        if: steps.paths_filter.outputs.pathA == 'true'
        run: echo "PATHA=true" >> $GITHUB_ENV

      - name: Set PATHB
        if: steps.paths_filter.outputs.pathB == 'true'
        run: echo "PATHB=true" >> $GITHUB_ENV

      # Example step that uses the set environment variables
      - name: Use the Environment Variables
        run: |
          echo "Path A changed: ${{ env.PATHA }}"
          echo "Path B changed: ${{ env.PATHB }}"
